### PR TITLE
add UML model/diagram

### PR DESCRIPTION
**Pull request by cportele**

### CODE REVIEW

**Comment by cportele** [comment]
Link to updated HTML: https://cdn.rawgit.com/opengeospatial/WFS_FES/cp-uml/docs/17-069.html

**Comment by MortenBorrebaek** [comment]
Quite hard to understand the UML model for the requirements in the Core (in figure 1). Please add some explanatory text.

**Comment by cportele** [comment]
@MortenBorrebaek - OK, I will add some descriptive text. I thought the diagram was more-or-less self-explanatory when you read the requirements :smile:.

**Comment by cportele** [comment]
@MortenBorrebaek - Please check, if the description is sufficient and propose changes, if not. Thanks!

**Pull request merged**
